[package]
name = "guess-note"
version = "0.1.0"
authors = ["Kitsu <mail@kitsu.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midir = "0.7.0"
anyhow = "1.0.40"
argh = "0.1.4"
rand = "0.8.3"
